coverage:
  precision: 0
  round: down
  range: "90...100"

  status:
    project:
      target: auto
      only_pulls: true
    patch: no
    changes: no

comment:
  layout: "header, diff, changes, tree"
  behavior: default

ignore:
 - "extern"
 - "tests"
