pr:
- master

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: GAP
  steps:
  - script: ci/azure-gap.sh
    displayName: 'Running the Semigroups package for GAP tests in docker container. . .'

- job: 
  steps:
  - script: |
      sudo apt-get install -y ccache
    displayName: "Install dependencies . . ."
  - script: |
      mkdir -p m4 && ./autogen.sh && ./configure 
    displayName: "Configure . . ."
  - script: |
      ccache -z && make -j4 && ccache -s
    displayName: "Build libsemigroups . . ."
  - script: |
      make test_all -j4
    displayName: "Build test_all . . ."
  - script: |
      ./test_all "[quick],[standard]"
    displayName: "Run the quick and standard tests . . ."
